# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8154aca148a9bb5aabe1e9a336e16c5e2908a4cafdcb4874ee899f835f251ab95a873c2c901fe2b427a1bf3708ba8df77bd440d997c40a44c877371637817db7

test:
  secret_key_base: 39ddba643f7740b9126c082fb16145b528c73853cdc0bafed2b162131f3c1be65b1e8fd2f5c321c64b90b6460cfd613beb830dffcc56030e7e8ed2c4eebb97d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
